run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec
    - stylecheck
    - revive
    - gocyclo
    - misspell
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  revive:
    confidence: 0.8

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

